# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIv7.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1193, 801)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.graphclass1 = PyQtGraphWid1(self.centralwidget)
        self.graphclass1.setObjectName(_fromUtf8("graphclass1"))
        self.gridLayout.addWidget(self.graphclass1, 0, 0, 1, 1)
        self.graphclass2 = PyQtGraphWid2(self.centralwidget)
        self.graphclass2.setObjectName(_fromUtf8("graphclass2"))
        self.gridLayout.addWidget(self.graphclass2, 0, 1, 1, 1)
        self.graphclass3 = PyQtGraphWid3(self.centralwidget)
        self.graphclass3.setObjectName(_fromUtf8("graphclass3"))
        self.gridLayout.addWidget(self.graphclass3, 1, 0, 1, 1)
        self.graphclass4 = PyQtGraphWid4(self.centralwidget)
        self.graphclass4.setObjectName(_fromUtf8("graphclass4"))
        self.gridLayout.addWidget(self.graphclass4, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFichier = QtGui.QMenu(self.menubar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuImage = QtGui.QMenu(self.menubar)
        self.menuImage.setObjectName(_fromUtf8("menuImage"))
        self.menuFond = QtGui.QMenu(self.menubar)
        self.menuFond.setObjectName(_fromUtf8("menuFond"))
        self.menuAfficher_cacher = QtGui.QMenu(self.menubar)
        self.menuAfficher_cacher.setObjectName(_fromUtf8("menuAfficher_cacher"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenMono = QtGui.QAction(MainWindow)
        self.actionOpenMono.setObjectName(_fromUtf8("actionOpenMono"))
        self.actionOpenMulti = QtGui.QAction(MainWindow)
        self.actionOpenMulti.setObjectName(_fromUtf8("actionOpenMulti"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionOpenImg1 = QtGui.QAction(MainWindow)
        self.actionOpenImg1.setObjectName(_fromUtf8("actionOpenImg1"))
        self.actionOpenImg2 = QtGui.QAction(MainWindow)
        self.actionOpenImg2.setObjectName(_fromUtf8("actionOpenImg2"))
        self.actionOpenImg3 = QtGui.QAction(MainWindow)
        self.actionOpenImg3.setObjectName(_fromUtf8("actionOpenImg3"))
        self.actionOpenImg4 = QtGui.QAction(MainWindow)
        self.actionOpenImg4.setObjectName(_fromUtf8("actionOpenImg4"))
        self.actionBackAll = QtGui.QAction(MainWindow)
        self.actionBackAll.setObjectName(_fromUtf8("actionBackAll"))
        self.actionBack1 = QtGui.QAction(MainWindow)
        self.actionBack1.setObjectName(_fromUtf8("actionBack1"))
        self.actionBack2 = QtGui.QAction(MainWindow)
        self.actionBack2.setObjectName(_fromUtf8("actionBack2"))
        self.actionBack3 = QtGui.QAction(MainWindow)
        self.actionBack3.setObjectName(_fromUtf8("actionBack3"))
        self.actionBack4 = QtGui.QAction(MainWindow)
        self.actionBack4.setObjectName(_fromUtf8("actionBack4"))
        self.actionCacher1 = QtGui.QAction(MainWindow)
        self.actionCacher1.setObjectName(_fromUtf8("actionCacher1"))
        self.actionCacher2 = QtGui.QAction(MainWindow)
        self.actionCacher2.setObjectName(_fromUtf8("actionCacher2"))
        self.actionCacher3 = QtGui.QAction(MainWindow)
        self.actionCacher3.setObjectName(_fromUtf8("actionCacher3"))
        self.actionCacher4 = QtGui.QAction(MainWindow)
        self.actionCacher4.setObjectName(_fromUtf8("actionCacher4"))
        self.actionFondhide1 = QtGui.QAction(MainWindow)
        self.actionFondhide1.setObjectName(_fromUtf8("actionFondhide1"))
        self.actionFondhide2 = QtGui.QAction(MainWindow)
        self.actionFondhide2.setObjectName(_fromUtf8("actionFondhide2"))
        self.actionFondhide3 = QtGui.QAction(MainWindow)
        self.actionFondhide3.setObjectName(_fromUtf8("actionFondhide3"))
        self.actionFondhide4 = QtGui.QAction(MainWindow)
        self.actionFondhide4.setObjectName(_fromUtf8("actionFondhide4"))
        self.actionCacherAll = QtGui.QAction(MainWindow)
        self.actionCacherAll.setObjectName(_fromUtf8("actionCacherAll"))
        self.actionFondhideAll = QtGui.QAction(MainWindow)
        self.actionFondhideAll.setObjectName(_fromUtf8("actionFondhideAll"))
        self.menuFichier.addAction(self.actionOpenMono)
        self.menuFichier.addAction(self.actionOpenMulti)
        self.menuFichier.addAction(self.actionQuit)
        self.menuImage.addAction(self.actionOpenImg1)
        self.menuImage.addAction(self.actionOpenImg2)
        self.menuImage.addAction(self.actionOpenImg3)
        self.menuImage.addAction(self.actionOpenImg4)
        self.menuFond.addAction(self.actionBackAll)
        self.menuFond.addAction(self.actionBack1)
        self.menuFond.addAction(self.actionBack2)
        self.menuFond.addAction(self.actionBack3)
        self.menuFond.addAction(self.actionBack4)
        self.menuAfficher_cacher.addAction(self.actionCacher1)
        self.menuAfficher_cacher.addAction(self.actionCacher2)
        self.menuAfficher_cacher.addAction(self.actionCacher3)
        self.menuAfficher_cacher.addAction(self.actionCacher4)
        self.menuAfficher_cacher.addAction(self.actionFondhide1)
        self.menuAfficher_cacher.addAction(self.actionFondhide2)
        self.menuAfficher_cacher.addAction(self.actionFondhide3)
        self.menuAfficher_cacher.addAction(self.actionFondhide4)
        self.menuAfficher_cacher.addAction(self.actionCacherAll)
        self.menuAfficher_cacher.addAction(self.actionFondhideAll)
        self.menubar.addAction(self.menuFichier.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFond.menuAction())
        self.menubar.addAction(self.menuAfficher_cacher.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "H5viewer 3", None))
        self.menuFichier.setTitle(_translate("MainWindow", "Fichier", None))
        self.menuImage.setTitle(_translate("MainWindow", "Image", None))
        self.menuFond.setTitle(_translate("MainWindow", "Fond", None))
        self.menuAfficher_cacher.setTitle(_translate("MainWindow", "Afficher/cacher", None))
        self.actionOpenMono.setText(_translate("MainWindow", "Ouvrir fichier une voie", None))
        self.actionOpenMulti.setText(_translate("MainWindow", "Ouvrir fichier multi-voies", None))
        self.actionQuit.setText(_translate("MainWindow", "Quitter", None))
        self.actionOpenImg1.setText(_translate("MainWindow", "Nouvelle image 1", None))
        self.actionOpenImg2.setText(_translate("MainWindow", "Nouvelle image 2", None))
        self.actionOpenImg3.setText(_translate("MainWindow", "Nouvelle image 3", None))
        self.actionOpenImg4.setText(_translate("MainWindow", "Nouvelle image 4", None))
        self.actionBackAll.setText(_translate("MainWindow", "Charger fond multi-voies", None))
        self.actionBack1.setText(_translate("MainWindow", "Charger fond image 1", None))
        self.actionBack2.setText(_translate("MainWindow", "Charger fond image 2", None))
        self.actionBack3.setText(_translate("MainWindow", "Charger fond image 3", None))
        self.actionBack4.setText(_translate("MainWindow", "Charger fond image 4", None))
        self.actionCacher1.setText(_translate("MainWindow", "Image 1", None))
        self.actionCacher2.setText(_translate("MainWindow", "Image 2", None))
        self.actionCacher3.setText(_translate("MainWindow", "Image 3", None))
        self.actionCacher4.setText(_translate("MainWindow", "Image 4", None))
        self.actionFondhide1.setText(_translate("MainWindow", "Fond 1", None))
        self.actionFondhide2.setText(_translate("MainWindow", "Fond 2", None))
        self.actionFondhide3.setText(_translate("MainWindow", "Fond 3", None))
        self.actionFondhide4.setText(_translate("MainWindow", "Fond 4", None))
        self.actionCacherAll.setText(_translate("MainWindow", "Toutes les images", None))
        self.actionFondhideAll.setText(_translate("MainWindow", "Tous les fond", None))

from H5viewer4_Widget import PyQtGraphWid1, PyQtGraphWid2, PyQtGraphWid3, PyQtGraphWid4
